name: Daily Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}
      SCKEY: ${{ secrets.SCKEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt  # 如果有依赖需要安装，请添加相应的命令

      - name: Run Daily Checkin
        run: |
          python main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          SCKEY: ${{ secrets.SCKEY }}

      - name: Notify Server酱
        if: ${{ secrets.SCKEY != '' }}
        run: curl -sS -X POST "https://sc.ftqq.com/${{ secrets.SCKEY }}.send" -d "text=GitHub Actions Daily Checkin&desp=Checkin result: ${{ job.status }}"

        
